/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\assets\MinecraftLever.glb -o .\src\components\Model.jsx --root assets 
*/

import React, { useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useSpring, animated } from "@react-spring/three";
import * as THREE from "three";

export function Model({ onToggle, ...props }) {
    const { nodes, materials } = useGLTF("assets/MinecraftLever.glb");
    const [active, setActive] = useState(false);
    const { rotation } = useSpring({
        rotation: active ? [0, 0, 1.573] : [0, 0, 0.573],
    });

    const handleClick = () => {
        setActive(!active);
        onToggle(!active);
    };

    return (
        <group {...props} dispose={null} onClick={handleClick}>
            <group position={[0, -0.383, 0]}>
                <group position={[0, 0.383, 0]} rotation={[0, 0, -1.05]}>
                    <animated.mesh
                        geometry={nodes.lever_arm.geometry}
                        material={materials["Material.002"]}
                        rotation={rotation}
                        scale={[0.605, 0.1, 0.1]}
                    />
                </group>
                <mesh
                    geometry={nodes.base_quad.geometry}
                    material={materials["Material.001"]}
                    position={[0, 0.384, 0]}
                    scale={[0.15, 0.502, 0.4]}
                />
            </group>
        </group>
    );
}

useGLTF.preload("assets/MinecraftLever.glb");
