/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\public\assets\room with desk.glb -o .\src\components\Room2.jsx --shadows 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations, useHelper } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from "three"

export function Room({lightOn, ...props}) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/assets/room with desk.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  
  const lightRef = React.useRef();
  useHelper(lightRef, THREE.SpotLightHelper, 1)

  React.useEffect(() => {
    Object.entries(materials).forEach(([name, material]) => {
      if (material instanceof THREE.MeshStandardMaterial && name !== 'lamp light' && name !== 'torchlight' && name !== 'Material.004') {
        material.emissive = new THREE.Color(0x0000);
      } else {
        console.log(typeof material)
      }
    })
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty_bend_paper_sheet" position={[-2.382, 2.006, -6.77]} rotation={[0, -1.134, 1.606]}>
          <mesh name="paper_sheet" castShadow receiveShadow geometry={nodes.paper_sheet.geometry} material={materials.pagesonthedesk} rotation={[1.581, -0.035, -1.57]} scale={[4.8, 5.1, 7.2]} />
        </group>
        <group name="Empty_bend_paper_sheet001" position={[-2.443, 2.031, -6.543]} rotation={[0.342, -1.386, 2.011]}>
          <mesh name="paper_sheet001" castShadow receiveShadow geometry={nodes.paper_sheet001.geometry} material={materials.pagesonthedesk} rotation={[1.581, -0.035, -1.57]} scale={[4.8, 5.1, 7.2]} />
        </group>
        <group name="Empty002" position={[-1, 4.063, -9.25]} rotation={[1.913, -1.386, 2.011]}>
          <mesh name="paper_sheet002" castShadow receiveShadow geometry={nodes.paper_sheet002.geometry} material={materials.pagesonthedesk} rotation={[1.494, -0.029, -1.579]} scale={[4.8, 5.1, 6.418]} />
        </group>
        <group name="red_light005" position={[-4.095, 0.3, -9.188]}>
          <pointLight visible={lightOn} name="red_light005_Orientation" decay={2} color="#ff4a57" rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="red_light006" position={[-4.095, 2.622, -9.188]}>
          <pointLight visible={lightOn} name="red_light006_Orientation" decay={2} color="#ff4a57" rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="red_light007" position={[-4.095, 4.64, -9.188]}>
          <pointLight visible={lightOn} name="red_light007_Orientation" decay={2} color="#ff4a57" rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="red_light008" position={[-4.095, 6.657, -9.188]}>
          <pointLight visible={lightOn} name="red_light008_Orientation" decay={2} color="#ff4a57" rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <mesh name="floor" castShadow receiveShadow geometry={nodes.floor.geometry} material={materials.floor} scale={[1.333, 1, 1.333]} />
        <mesh name="desk" castShadow receiveShadow geometry={nodes.desk.geometry} material={materials.desk} position={[0, 0, -10]} scale={[3, 3, 1]} />
        <mesh name="Book_stand" castShadow receiveShadow geometry={nodes.Book_stand.geometry} material={materials['Material.001']} position={[0, 0.958, -7.003]} />
        <mesh name="Cube019" castShadow receiveShadow geometry={nodes.Cube019.geometry} material={nodes.Cube019.material} position={[0, 5.2, -11]} scale={[9.99, 5.2, 1]} />
        <mesh name="bookshelf" castShadow receiveShadow geometry={nodes.bookshelf.geometry} material={materials['book shelf']} position={[0, 7, -9.5]} scale={[3, 0.15, 0.5]} />
        <mesh name="Cube021" castShadow receiveShadow geometry={nodes.Cube021.geometry} material={nodes.Cube021.material} position={[-9, 5.2, 0]} rotation={[0, Math.PI / 2, 0]} scale={[9.99, 5.2, 1]} />
        <mesh name="lever_s_pipe" castShadow receiveShadow geometry={nodes.lever_s_pipe.geometry} material={materials['eletric pipe']} position={[-7.9, 1.75, -2]} scale={[0.1, 1.75, 0.1]} />
        <group name="secondary_book002" position={[2.438, 2.267, -7.003]} rotation={[0, 1.309, 0]} scale={[7.21, 1.442, 5.047]}>
          <mesh name="Cube003" castShadow receiveShadow geometry={nodes.Cube003.geometry} material={materials['book ']} />
          <mesh name="Cube003_1" castShadow receiveShadow geometry={nodes.Cube003_1.geometry} material={materials['pages closed books']} />
        </group>
        <mesh name="Cup" castShadow receiveShadow geometry={nodes.Cup.geometry} material={materials.cup} position={[-1.625, 2.287, -6.75]} scale={1.82} />
        <mesh name="eletric_tile_bottom" castShadow receiveShadow geometry={nodes.eletric_tile_bottom.geometry} material={materials['eletric tile bottom']} position={[-7.5, 0.063, -2]} scale={[8, 1, 8]}>
          <group name="eletric_tile_top" position={[0, 0.118, 0]}>
            <mesh name="Cube057" castShadow receiveShadow geometry={nodes.Cube057.geometry} material={materials['eletric tile top']} />
            <mesh name="Cube057_1" castShadow receiveShadow geometry={nodes.Cube057_1.geometry} material={materials['eletric tile light']} />
          </group>
        </mesh>
        <mesh name="eletric_torch_stick" castShadow receiveShadow geometry={nodes.eletric_torch_stick.geometry} material={materials['torch body']} position={[-7.5, 0.1, -2]} scale={[1.6, 6.4, 1.6]}>
          <mesh name="eletric_torch_light" castShadow receiveShadow geometry={nodes.eletric_torch_light.geometry} material={materials.torchlight} material-emissiveIntensity={lightOn ? 10 : 0} position={[0, 0.141, 0]} scale={[1, 0.25, 1]}>
            <mesh name="torch_red_bottom" castShadow receiveShadow geometry={nodes.torch_red_bottom.geometry} material={materials.torchredglass} position={[0, -0.062, 0]} scale={[1, 0.5, 1]} />
            <mesh name="torch_red_midpart" castShadow receiveShadow geometry={nodes.torch_red_midpart.geometry} material={materials.torchredglass} position={[0.098, 0, 0.063]} rotation={[Math.PI, -1.571, 0]} scale={[-0.15, -1, -0.6]} />
            <mesh name="torch_red_top" castShadow receiveShadow geometry={nodes.torch_red_top.geometry} material={materials.torchredglass} position={[0, 0.124, 0]} scale={[1, 0.5, 1]} />
          </mesh>
        </mesh>
        <mesh name="eletric_tile_bottom001" castShadow receiveShadow geometry={nodes.eletric_tile_bottom001.geometry} material={materials['eletric tile bottom']} position={[-7.5, 0.063, -5.6]} scale={[8, 1, 8]}>
          <group name="eletric_tile_top001" position={[0, 0.118, 0]}>
            <mesh name="Cube064" castShadow receiveShadow geometry={nodes.Cube064.geometry} material={materials['eletric tile top']} />
            <mesh name="Cube064_1" castShadow receiveShadow geometry={nodes.Cube064_1.geometry} material={materials['eletric tile light']} />
          </group>
        </mesh>
        <mesh name="eletric_torch_stick001" castShadow receiveShadow geometry={nodes.eletric_torch_stick001.geometry} material={materials['torch body']} position={[-7.5, 0.1, -5.6]} scale={[1.6, 6.4, 1.6]}>
          <mesh name="eletric_torch_light001" castShadow receiveShadow geometry={nodes.eletric_torch_light001.geometry} material={materials.torchlight} material-emissiveIntensity={lightOn ? 10 : 0} position={[0, 0.141, 0]} scale={[1, 0.25, 1]}>
            <mesh name="torch_red_bottom001" castShadow receiveShadow geometry={nodes.torch_red_bottom001.geometry} material={materials.torchredglass} position={[0, -0.062, 0]} scale={[1, 0.5, 1]} />
            <mesh name="torch_red_midpart001" castShadow receiveShadow geometry={nodes.torch_red_midpart001.geometry} material={materials.torchredglass} position={[0.098, 0, 0.063]} rotation={[Math.PI, -1.571, 0]} scale={[-0.15, -1, -0.6]} />
            <mesh name="torch_red_top001" castShadow receiveShadow geometry={nodes.torch_red_top001.geometry} material={materials.torchredglass} position={[0, 0.124, 0]} scale={[1, 0.5, 1]} />
          </mesh>
        </mesh>
        <mesh name="eletric_tile_bottom002" castShadow receiveShadow geometry={nodes.eletric_tile_bottom002.geometry} material={materials['eletric tile bottom']} position={[-7.5, 0.063, -9.463]} scale={[8, 1, 8]}>
          <group name="eletric_tile_top002" position={[0, 0.118, 0]}>
            <mesh name="Cube071" castShadow receiveShadow geometry={nodes.Cube071.geometry} material={materials['eletric tile top']} />
            <mesh name="Cube071_1" castShadow receiveShadow geometry={nodes.Cube071_1.geometry} material={materials['eletric tile light']} />
          </group>
        </mesh>
        <mesh name="eletric_torch_stick002" castShadow receiveShadow geometry={nodes.eletric_torch_stick002.geometry} material={materials['torch body']} position={[-7.5, 0.1, -9.463]} scale={[1.6, 6.4, 1.6]}>
          <mesh name="eletric_torch_light002" castShadow receiveShadow geometry={nodes.eletric_torch_light002.geometry} material={materials.torchlight} material-emissiveIntensity={lightOn ? 10 : 0} position={[0, 0.141, 0]} scale={[1, 0.25, 1]}>
            <mesh name="torch_red_bottom002" castShadow receiveShadow geometry={nodes.torch_red_bottom002.geometry} material={materials.torchredglass} position={[0, -0.062, 0]} scale={[1, 0.5, 1]} />
            <mesh name="torch_red_midpart002" castShadow receiveShadow geometry={nodes.torch_red_midpart002.geometry} material={materials.torchredglass} position={[0.098, 0, 0.063]} rotation={[Math.PI, -1.571, 0]} scale={[-0.15, -1, -0.6]} />
            <mesh name="torch_red_top002" castShadow receiveShadow geometry={nodes.torch_red_top002.geometry} material={materials.torchredglass} position={[0, 0.124, 0]} scale={[1, 0.5, 1]} />
          </mesh>
        </mesh>
        <mesh name="eletric_tile_bottom003" castShadow receiveShadow geometry={nodes.eletric_tile_bottom003.geometry} material={materials['eletric tile bottom']} position={[-3.813, 0.063, -9.5]} scale={[8, 1, 8]}>
          <group name="eletric_top003" position={[0, 0.118, 0]}>
            <mesh name="Cube078" castShadow receiveShadow geometry={nodes.Cube078.geometry} material={materials['eletric tile top']} />
            <mesh name="Cube078_1" castShadow receiveShadow geometry={nodes.Cube078_1.geometry} material={materials['eletric tile light']} />
          </group>
        </mesh>
        <mesh name="eletric_torch_stick003" castShadow receiveShadow geometry={nodes.eletric_torch_stick003.geometry} material={materials['torch body']} position={[-3.813, 0.1, -9.5]} scale={[1.6, 6.4, 1.6]}>
          <mesh name="eletric_torch_light003" castShadow receiveShadow geometry={nodes.eletric_torch_light003.geometry} material={materials.torchlight} material-emissiveIntensity={lightOn ? 10 : 0} position={[0, 0.141, 0]} scale={[1, 0.25, 1]}>
            <mesh name="torch_red_bottom003" castShadow receiveShadow geometry={nodes.torch_red_bottom003.geometry} material={materials.torchredglass} position={[0, -0.062, 0]} scale={[1, 0.5, 1]} />
            <mesh name="torch_red_midpart003" castShadow receiveShadow geometry={nodes.torch_red_midpart003.geometry} material={materials.torchredglass} position={[0.098, 0, 0.062]} rotation={[Math.PI, -1.571, 0]} scale={[-0.15, -1, -0.6]} />
            <mesh name="torch_red_top003" castShadow receiveShadow geometry={nodes.torch_red_top003.geometry} material={materials.torchredglass} position={[0, 0.124, 0]} scale={[1, 0.5, 1]} />
          </mesh>
        </mesh>
        <mesh name="lever_s_pipe001" castShadow receiveShadow geometry={nodes.lever_s_pipe001.geometry} material={materials['eletric pipe']} position={[-3.813, 1.75, -9.9]} rotation={[0, -Math.PI / 2, 0]} scale={[0.1, 1.75, 0.1]} />
        <mesh name="lever_s_pipe002" castShadow receiveShadow geometry={nodes.lever_s_pipe002.geometry} material={materials['eletric pipe']} position={[-3.813, 5.238, -9.9]} rotation={[0, -Math.PI / 2, 0]} scale={[0.1, 1.75, 0.1]} />
        <group name="secondary_book019" position={[2.438, 2.094, -7.003]} rotation={[0, 1.228, 0]} scale={[7.21, 1.442, 5.047]}>
          <mesh name="Cube044" castShadow receiveShadow geometry={nodes.Cube044.geometry} material={materials['book .001']} />
          <mesh name="Cube044_1" castShadow receiveShadow geometry={nodes.Cube044_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book001" position={[2.438, 2.425, -7.003]} rotation={[-Math.PI, 1.135, -Math.PI]} scale={[5.047, 1.009, 3.533]}>
          <mesh name="Cube045" castShadow receiveShadow geometry={nodes.Cube045.geometry} material={materials['book .002']} />
          <mesh name="Cube045_1" castShadow receiveShadow geometry={nodes.Cube045_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book003" position={[1.625, 2.188, -7.003]} rotation={[0, 1.483, 0]} scale={[5.047, 1.009, 3.533]}>
          <mesh name="Cube046" castShadow receiveShadow geometry={nodes.Cube046.geometry} material={materials['book .003']} />
          <mesh name="Cube046_1" castShadow receiveShadow geometry={nodes.Cube046_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book018" position={[1.625, 2.063, -7.003]} rotation={[0, 1.57, 0]} scale={[5.047, 1.009, 3.533]}>
          <mesh name="Cube047" castShadow receiveShadow geometry={nodes.Cube047.geometry} material={materials['book .004']} />
          <mesh name="Cube047_1" castShadow receiveShadow geometry={nodes.Cube047_1.geometry} material={materials['pages closed books']} />
        </group>
        <mesh name="ink_jar001" castShadow receiveShadow geometry={nodes.ink_jar001.geometry} material={materials['globe base']} position={[-1.792, 2, -8.31]} scale={5.326}>
          <mesh name="sphere_on_the_table" castShadow receiveShadow geometry={nodes.sphere_on_the_table.geometry} material={materials['globe ']} position={[-0.004, 0.244, 0]} rotation={[0.094, 0.084, -0.013]} scale={0.124}>
            <mesh name="sphere_on_the_table001" castShadow receiveShadow geometry={nodes.sphere_on_the_table001.geometry} material={materials['globe arm vertical axis']} rotation={[-0.719, -0.321, -0.141]} scale={1.032} />
          </mesh>
        </mesh>
        <mesh name="ink_jar002" castShadow receiveShadow geometry={nodes.ink_jar002.geometry} material={materials['globe base.001']} position={[1.629, 2.25, -7.063]} rotation={[0, -1.028, 0]} scale={2.556} />
        <mesh name="minecraft_pick_axe" castShadow receiveShadow geometry={nodes.minecraft_pick_axe.geometry} material={materials['Material.003']} position={[-2.09, 2.063, -6.896]} rotation={[-Math.PI / 2, 0, 0.311]} scale={[0.911, 0.911, 0.273]} />
        <mesh name="redstone_dust_tile" castShadow receiveShadow geometry={nodes.redstone_dust_tile.geometry} material={materials['Material.004']} material-emissiveIntensity={lightOn ? 10: 0} position={[-7.5, 0.034, -3.228]} scale={[8, 3.2, 8]} />
        <mesh name="redstone_dust_tile001" castShadow receiveShadow geometry={nodes.redstone_dust_tile001.geometry} material={materials['Material.004']} material-emissiveIntensity={lightOn ? 10: 0} position={[-7.5, 0.034, -4.272]} scale={[8, 3.2, 8]} />
        <mesh name="redstone_dust_tile002" castShadow receiveShadow geometry={nodes.redstone_dust_tile002.geometry} material={materials['Material.004']} material-emissiveIntensity={lightOn ? 10: 0} position={[-7.5, 0.034, -7.103]} scale={[8, 3.2, 8]} />
        <mesh name="redstone_dust_tile003" castShadow receiveShadow geometry={nodes.redstone_dust_tile003.geometry} material={materials['Material.004']} material-emissiveIntensity={lightOn ? 10: 0} position={[-7.5, 0.034, -8.147]} scale={[8, 3.2, 8]} />
        <mesh name="redstone_dust_tile005" castShadow receiveShadow geometry={nodes.redstone_dust_tile005.geometry} material={materials['Material.004']} material-emissiveIntensity={lightOn ? 10: 0} position={[-5.228, 0.034, -9.5]} rotation={[0, Math.PI / 2, 0]} scale={[8, 3.2, 8]} />
        <mesh name="redstone_dust_tile004" castShadow receiveShadow geometry={nodes.redstone_dust_tile004.geometry} material={materials['Material.004']} material-emissiveIntensity={lightOn ? 10: 0} position={[-6.272, 0.034, -9.5]} rotation={[0, Math.PI / 2, 0]} scale={[8, 3.2, 8]} />
        <group name="secondary_book017" position={[-1.814, 7.6, -9.563]} rotation={[3.141, 0, -1.313]} scale={[7.066, 1.413, 4.946]}>
          <mesh name="Cube004" castShadow receiveShadow geometry={nodes.Cube004.geometry} material={materials['book .002']} />
          <mesh name="Cube004_1" castShadow receiveShadow geometry={nodes.Cube004_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book005" position={[-1.55, 7.6, -9.563]} rotation={[3.141, 0, -Math.PI / 2]} scale={[7.066, 1.413, 4.946]}>
          <mesh name="Cube023" castShadow receiveShadow geometry={nodes.Cube023.geometry} material={materials['book .002']} />
          <mesh name="Cube023_1" castShadow receiveShadow geometry={nodes.Cube023_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book006" position={[-1.356, 7.6, -9.563]} rotation={[3.141, 0, -Math.PI / 2]} scale={[7.066, 1.413, 4.946]}>
          <mesh name="Cube024" castShadow receiveShadow geometry={nodes.Cube024.geometry} material={materials['book .002']} />
          <mesh name="Cube024_1" castShadow receiveShadow geometry={nodes.Cube024_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book007" position={[-1.163, 7.6, -9.563]} rotation={[3.141, 0, -Math.PI / 2]} scale={[7.066, 1.413, 4.946]}>
          <mesh name="Cube027" castShadow receiveShadow geometry={nodes.Cube027.geometry} material={materials['book .002']} />
          <mesh name="Cube027_1" castShadow receiveShadow geometry={nodes.Cube027_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book008" position={[-0.969, 7.6, -9.563]} rotation={[3.141, 0, -Math.PI / 2]} scale={[7.066, 1.413, 4.946]}>
          <mesh name="Cube033" castShadow receiveShadow geometry={nodes.Cube033.geometry} material={materials['book .002']} />
          <mesh name="Cube033_1" castShadow receiveShadow geometry={nodes.Cube033_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book009" position={[-0.775, 7.6, -9.563]} rotation={[3.141, 0, -Math.PI / 2]} scale={[7.066, 1.413, 4.946]}>
          <mesh name="Cube034" castShadow receiveShadow geometry={nodes.Cube034.geometry} material={materials['book .002']} />
          <mesh name="Cube034_1" castShadow receiveShadow geometry={nodes.Cube034_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book010" position={[-0.581, 7.6, -9.563]} rotation={[3.141, 0, -Math.PI / 2]} scale={[7.066, 1.413, 4.946]}>
          <mesh name="Cube035" castShadow receiveShadow geometry={nodes.Cube035.geometry} material={materials['book .002']} />
          <mesh name="Cube035_1" castShadow receiveShadow geometry={nodes.Cube035_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book011" position={[-0.388, 7.6, -9.563]} rotation={[3.141, 0, -Math.PI / 2]} scale={[7.066, 1.413, 4.946]}>
          <mesh name="Cube038" castShadow receiveShadow geometry={nodes.Cube038.geometry} material={materials['book .002']} />
          <mesh name="Cube038_1" castShadow receiveShadow geometry={nodes.Cube038_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book012" position={[-0.194, 7.6, -9.563]} rotation={[3.141, 0, -Math.PI / 2]} scale={[7.066, 1.413, 4.946]}>
          <mesh name="Cube039" castShadow receiveShadow geometry={nodes.Cube039.geometry} material={materials['book .002']} />
          <mesh name="Cube039_1" castShadow receiveShadow geometry={nodes.Cube039_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book013" position={[0, 7.6, -9.563]} rotation={[3.141, 0, -Math.PI / 2]} scale={[7.066, 1.413, 4.946]}>
          <mesh name="Cube040" castShadow receiveShadow geometry={nodes.Cube040.geometry} material={materials['book .002']} />
          <mesh name="Cube040_1" castShadow receiveShadow geometry={nodes.Cube040_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book014" position={[0.194, 7.6, -9.563]} rotation={[3.141, 0, -Math.PI / 2]} scale={[7.066, 1.413, 4.946]}>
          <mesh name="Cube043" castShadow receiveShadow geometry={nodes.Cube043.geometry} material={materials['book .002']} />
          <mesh name="Cube043_1" castShadow receiveShadow geometry={nodes.Cube043_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book015" position={[0.387, 7.6, -9.563]} rotation={[3.141, 0, -Math.PI / 2]} scale={[7.066, 1.413, 4.946]}>
          <mesh name="Cube048" castShadow receiveShadow geometry={nodes.Cube048.geometry} material={materials['book .002']} />
          <mesh name="Cube048_1" castShadow receiveShadow geometry={nodes.Cube048_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book016" position={[0.581, 7.6, -9.563]} rotation={[3.141, 0, -Math.PI / 2]} scale={[7.066, 1.413, 4.946]}>
          <mesh name="Cube049" castShadow receiveShadow geometry={nodes.Cube049.geometry} material={materials['book .002']} />
          <mesh name="Cube049_1" castShadow receiveShadow geometry={nodes.Cube049_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book020" position={[0.775, 7.6, -9.563]} rotation={[3.141, 0, -Math.PI / 2]} scale={[7.066, 1.413, 4.946]}>
          <mesh name="Cube050" castShadow receiveShadow geometry={nodes.Cube050.geometry} material={materials['book .002']} />
          <mesh name="Cube050_1" castShadow receiveShadow geometry={nodes.Cube050_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book021" position={[0.969, 7.6, -9.563]} rotation={[3.141, 0, -Math.PI / 2]} scale={[7.066, 1.413, 4.946]}>
          <mesh name="Cube051" castShadow receiveShadow geometry={nodes.Cube051.geometry} material={materials['book .002']} />
          <mesh name="Cube051_1" castShadow receiveShadow geometry={nodes.Cube051_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book022" position={[1.162, 7.6, -9.563]} rotation={[3.141, 0, -Math.PI / 2]} scale={[7.066, 1.413, 4.946]}>
          <mesh name="Cube052" castShadow receiveShadow geometry={nodes.Cube052.geometry} material={materials['book .002']} />
          <mesh name="Cube052_1" castShadow receiveShadow geometry={nodes.Cube052_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="secondary_book023" position={[1.356, 7.6, -9.563]} rotation={[3.141, 0, -Math.PI / 2]} scale={[7.066, 1.413, 4.946]}>
          <mesh name="Cube053" castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials['book .002']} />
          <mesh name="Cube053_1" castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials['pages closed books']} />
        </group>
        <group name="lamp001" position={[-1.4, 5.649, -7.3]} scale={[0.25, 0.2, 0.5]}>
          <mesh name="Cube036" castShadow receiveShadow geometry={nodes.Cube036.geometry} material={materials.lamp} />
          <mesh name="Cube036_1" castShadow receiveShadow geometry={nodes.Cube036_1.geometry} material={materials['lamp light']} material-emissiveIntensity={lightOn ? 5 : 0} />
          <group name="lamp_light001" position={[0, -4, 0.001]} scale={[1.483, 3.75, 1.74]}>
            <spotLight visible={lightOn} shadow-mapSize-width={2048} shadow-mapSize-height={2048} shadow-bias={-0.001} castShadow angle={1.1} penumbra={0.8} decay={2} intensity={15} color="#ffe9a6" rotation={[-Math.PI / 2, 0, 0]} target={nodes.lamp_light001_Orientation.target}>
              <primitive object={nodes.lamp_light001_Orientation.target} position={[0, 0, -1]} />
            </spotLight>
          </group>
        </group>
        <group name="lamp002" position={[0, 5.649, -7.3]} scale={[0.25, 0.2, 0.5]}>
          <mesh name="Cube041" castShadow receiveShadow geometry={nodes.Cube041.geometry} material={materials.lamp} />
          <mesh name="Cube041_1" castShadow receiveShadow geometry={nodes.Cube041_1.geometry} material={materials['lamp light']} material-emissiveIntensity={lightOn ? 5 : 0} />
          <group name="lamp_light002" position={[0, -4, 0.001]} scale={[0.371, 0.75, 0.87]}>
            <spotLight visible={lightOn} shadow-mapSize-width={2048} shadow-mapSize-height={2048} shadow-bias={-0.001} castShadow angle={1.1} penumbra={0.8} decay={2} intensity={15} color="#ffe9a6" rotation={[-Math.PI / 2, 0, 0]} target={nodes.lamp_light002_Orientation.target}>
              <primitive object={nodes.lamp_light002_Orientation.target} position={[0, 0, -1]} />
            </spotLight>
          </group>
        </group>
        <group name="lamp003" position={[1.4, 5.649, -7.3]} scale={[0.25, 0.2, 0.5]}>
          <mesh name="Cube042" castShadow receiveShadow geometry={nodes.Cube042.geometry} material={materials.lamp} />
          <mesh name="Cube042_1" castShadow receiveShadow geometry={nodes.Cube042_1.geometry} material={materials['lamp light']} material-emissiveIntensity={lightOn ? 5 : 0} />
          <group name="lamp_light003" position={[0, -4, 0.001]} scale={[0.371, 0.75, 0.87]}>
            <spotLight visible={lightOn} shadow-mapSize-width={2048} shadow-mapSize-height={2048} shadow-bias={-0.001} castShadow angle={1.1} penumbra={0.8} decay={2} intensity={15} color="#ffe9a6" rotation={[-Math.PI / 2, 0, 0]} target={nodes.lamp_light003_Orientation.target}>
              <primitive object={nodes.lamp_light003_Orientation.target} position={[0, 0, -1]} />
            </spotLight>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/room with desk.glb')
