/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\assets\room with desk.glb --shadows -o .\src\components\Room.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera, useAnimations, useHelper } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { SpotLightHelper } from 'three'

export function Room({lightOn, ...props}) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/assets/room with desk.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  const lightRef = React.useRef();
  useHelper(lightRef, SpotLightHelper, 1)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Camera" position={[0.021, 3.825, -5.262]} rotation={[0.923, 0.004, -0.006]}>
          <PerspectiveCamera name="Camera_Orientation" makeDefault={false} far={1000} near={0.1} fov={58.716} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="Camera001" position={[-3.889, 4.028, -1.927]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <PerspectiveCamera name="Camera001_Orientation" makeDefault={false} far={1000} near={0.1} fov={32.269} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="Empty" position={[-2.382, 2.006, -6.77]} rotation={[0, -1.134, 1.606]}>
          <mesh name="paper_sheet" castShadow receiveShadow geometry={nodes.paper_sheet.geometry} material={nodes.paper_sheet.material} rotation={[1.581, -0.035, -1.57]} scale={[4.8, 5.1, 7.2]} />
        </group>
        <group name="Empty001" position={[-2.443, 2.031, -6.543]} rotation={[0.342, -1.386, 2.011]}>
          <mesh name="paper_sheet001" castShadow receiveShadow geometry={nodes.paper_sheet001.geometry} material={nodes.paper_sheet001.material} rotation={[1.581, -0.035, -1.57]} scale={[4.8, 5.1, 7.2]} />
        </group>
        <group name="Empty002" position={[-1, 4.063, -9.25]} rotation={[1.913, -1.386, 2.011]}>
          <mesh name="paper_sheet002" castShadow receiveShadow geometry={nodes.paper_sheet002.geometry} material={nodes.paper_sheet002.material} rotation={[1.494, -0.029, -1.579]} scale={[4.8, 5.1, 6.418]} />
        </group>
        <group name="red_light001" position={[-7.231, 2.784, -2]}>
          <pointLight visible={lightOn} name="red_light001_Orientation" decay={2} color="#ff4a57" rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="red_light002" position={[-7.231, 0.3, -2]}>
          <pointLight visible={lightOn} name="red_light002_Orientation" decay={2} color="#ff4a57" rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="red_light003" position={[-7.231, 0.3, -5.264]}>
          <pointLight visible={lightOn} name="red_light003_Orientation" decay={2} color="#ff4a57" rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="red_light004" position={[-7.231, 0.3, -8.528]}>
          <pointLight visible={lightOn} name="red_light004_Orientation" decay={2} color="#ff4a57" rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="red_light005" position={[-4.095, 0.3, -9.188]}>
          <pointLight visible={lightOn} name="red_light005_Orientation" decay={2} color="#ff4a57" rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="red_light006" position={[-4.095, 2.622, -9.188]}>
          <pointLight visible={lightOn} name="red_light006_Orientation" decay={2} color="#ff4a57" rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="red_light007" position={[-4.095, 4.64, -9.188]}>
          <pointLight visible={lightOn} name="red_light007_Orientation" decay={2} color="#ff4a57" rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="red_light008" position={[-4.095, 6.657, -9.188]}>
          <pointLight visible={lightOn} name="red_light008_Orientation" decay={2} color="#ff4a57" rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <mesh name="floor" castShadow receiveShadow geometry={nodes.floor.geometry} material={materials['Material.002']} scale={[1.333, 1, 1.333]} />
        <mesh name="desk" castShadow receiveShadow geometry={nodes.desk.geometry} material={materials.desk} position={[0, 0, -10]} scale={[3, 3, 1]} />
        <mesh name="Book_stand" castShadow receiveShadow geometry={nodes.Book_stand.geometry} material={materials['Material.001']} position={[0, 0.958, -7.003]} />
        <mesh name="Cube019" castShadow receiveShadow geometry={nodes.Cube019.geometry} material={nodes.Cube019.material} position={[0, 5.2, -11]} scale={[9.99, 5.2, 1]} />
        <mesh name="bookshelf" castShadow receiveShadow geometry={nodes.bookshelf.geometry} material={nodes.bookshelf.material} position={[0, 7, -9.5]} scale={[3, 0.15, 0.5]} />
        <mesh name="Cube021" castShadow receiveShadow geometry={nodes.Cube021.geometry} material={nodes.Cube021.material} position={[-9, 5.2, 0]} rotation={[0, Math.PI / 2, 0]} scale={[9.99, 5.2, 1]} />
        <mesh name="sphere_on_the_table" castShadow receiveShadow geometry={nodes.sphere_on_the_table.geometry} material={nodes.sphere_on_the_table.material} position={[-1.813, 2.906, -8.313]} rotation={[0.007, -0.003, -0.004]} scale={0.47}>
          <mesh name="sphere_foots" castShadow receiveShadow geometry={nodes.sphere_foots.geometry} material={nodes.sphere_foots.material} position={[0.498, -0.58, 0.499]} rotation={[-0.011, 0.789, 0.006]} scale={1.489} />
        </mesh>
        <mesh name="lever_s_pipe" castShadow receiveShadow geometry={nodes.lever_s_pipe.geometry} material={nodes.lever_s_pipe.material} position={[-7.7, 1.75, -2]} scale={[0.1, 1.75, 0.1]} />
        <mesh name="secondary_book001" castShadow receiveShadow geometry={nodes.secondary_book001.geometry} material={nodes.secondary_book001.material} position={[2.438, 2.091, -7.003]} rotation={[0, 1.222, 0]} scale={[7.21, 1.442, 5.047]} />
        <mesh name="secondary_book002" castShadow receiveShadow geometry={nodes.secondary_book002.geometry} material={nodes.secondary_book002.material} position={[2.438, 2.267, -7.003]} rotation={[0, 1.309, 0]} scale={[7.21, 1.442, 5.047]} />
        <mesh name="secondary_book003" castShadow receiveShadow geometry={nodes.secondary_book003.geometry} material={nodes.secondary_book003.material} position={[2.438, 2.42, -7.003]} rotation={[-Math.PI, 1.134, -Math.PI]} scale={[5.047, 1.009, 3.533]} />
        <mesh name="secondary_book004" castShadow receiveShadow geometry={nodes.secondary_book004.geometry} material={nodes.secondary_book004.material} position={[-2, 7.6, -9.563]} rotation={[-Math.PI, 0, 1.745]} scale={[7.21, 1.442, 5.047]} />
        <mesh name="secondary_book005" castShadow receiveShadow geometry={nodes.secondary_book005.geometry} material={nodes.secondary_book005.material} position={[-1.731, 7.6, -9.563]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={[7.21, 1.442, 5.047]} />
        <mesh name="secondary_book006" castShadow receiveShadow geometry={nodes.secondary_book006.geometry} material={nodes.secondary_book006.material} position={[-1.538, 7.6, -9.563]} rotation={[-Math.PI, 0, 1.536]} scale={[7.21, 1.442, 5.047]} />
        <mesh name="secondary_book007" castShadow receiveShadow geometry={nodes.secondary_book007.geometry} material={nodes.secondary_book007.material} position={[-1.344, 7.6, -9.563]} rotation={[-Math.PI, 0, 1.536]} scale={[7.21, 1.442, 5.047]} />
        <mesh name="secondary_book008" castShadow receiveShadow geometry={nodes.secondary_book008.geometry} material={nodes.secondary_book008.material} position={[-1.15, 7.6, -9.563]} rotation={[-Math.PI, 0, 1.536]} scale={[7.21, 1.442, 5.047]} />
        <mesh name="secondary_book009" castShadow receiveShadow geometry={nodes.secondary_book009.geometry} material={nodes.secondary_book009.material} position={[-0.956, 7.6, -9.563]} rotation={[-Math.PI, 0, 1.536]} scale={[7.21, 1.442, 5.047]} />
        <mesh name="secondary_book010" castShadow receiveShadow geometry={nodes.secondary_book010.geometry} material={nodes.secondary_book010.material} position={[-0.762, 7.6, -9.563]} rotation={[-Math.PI, 0, 1.536]} scale={[7.21, 1.442, 5.047]} />
        <mesh name="secondary_book011" castShadow receiveShadow geometry={nodes.secondary_book011.geometry} material={nodes.secondary_book011.material} position={[-0.569, 7.6, -9.563]} rotation={[-Math.PI, 0, 1.536]} scale={[7.21, 1.442, 5.047]} />
        <mesh name="secondary_book012" castShadow receiveShadow geometry={nodes.secondary_book012.geometry} material={nodes.secondary_book012.material} position={[-0.375, 7.6, -9.563]} rotation={[-Math.PI, 0, 1.536]} scale={[7.21, 1.442, 5.047]} />
        <mesh name="secondary_book013" castShadow receiveShadow geometry={nodes.secondary_book013.geometry} material={nodes.secondary_book013.material} position={[-0.181, 7.6, -9.563]} rotation={[-Math.PI, 0, 1.536]} scale={[7.21, 1.442, 5.047]} />
        <mesh name="secondary_book014" castShadow receiveShadow geometry={nodes.secondary_book014.geometry} material={nodes.secondary_book014.material} position={[0.013, 7.6, -9.563]} rotation={[-Math.PI, 0, 1.536]} scale={[7.21, 1.442, 5.047]} />
        <mesh name="secondary_book015" castShadow receiveShadow geometry={nodes.secondary_book015.geometry} material={nodes.secondary_book015.material} position={[0.206, 7.6, -9.563]} rotation={[-Math.PI, 0, 1.536]} scale={[7.21, 1.442, 5.047]} />
        <mesh name="secondary_book016" castShadow receiveShadow geometry={nodes.secondary_book016.geometry} material={nodes.secondary_book016.material} position={[0.4, 7.6, -9.563]} rotation={[-Math.PI, 0, 1.536]} scale={[7.21, 1.442, 5.047]} />
        <mesh name="Cup" castShadow receiveShadow geometry={nodes.Cup.geometry} material={nodes.Cup.material} position={[-1.625, 2.287, -6.75]} scale={1.82} />
        <mesh name="ink_jar" castShadow receiveShadow geometry={nodes.ink_jar.geometry} material={nodes.ink_jar.material} position={[1.625, 2.25, -7]} scale={3.6} />
        <mesh name="secondary_book017" castShadow receiveShadow geometry={nodes.secondary_book017.geometry} material={nodes.secondary_book017.material} position={[1.625, 2.063, -7.003]} rotation={[0, 1.571, 0]} scale={[5.047, 1.009, 3.533]} />
        <mesh name="secondary_book018" castShadow receiveShadow geometry={nodes.secondary_book018.geometry} material={nodes.secondary_book018.material} position={[1.625, 2.188, -7.003]} rotation={[0, 1.484, 0]} scale={[5.047, 1.009, 3.533]} />
        <mesh name="lamp001" castShadow receiveShadow geometry={nodes.lamp001.geometry} material={nodes.lamp001.material} position={[-1.4, 5.649, -7.3]} scale={[0.25, 0.2, 0.5]}>
          <group name="lamp_light001" position={[0, -5, 0.001]} scale={[1.483, 3.75, 1.74]}>
            <spotLight visible={lightOn} ref={lightRef} castShadow angle={1.1} penumbra={0.8} decay={2} intensity={7} color="#ffe9a6" rotation={[-Math.PI / 2, 0, 0]} target={nodes.lamp_light001_Orientation.target}>
              <primitive object={nodes.lamp_light001_Orientation.target} position={[0, 0, -1]} />
            </spotLight>
          </group>
        </mesh>
        <mesh name="lamp004" castShadow receiveShadow geometry={nodes.lamp004.geometry} material={nodes.lamp004.material} position={[0, 5.649, -7.3]} scale={[0.25, 0.2, 0.5]}>
          <group name="lamp_light002" position={[0, -5, 0.001]} scale={[1.483, 3.75, 1.74]}>
            <spotLight visible={lightOn} castShadow angle={1.1} penumbra={0.8} decay={2} intensity={7} color="#ffe9a6" rotation={[-Math.PI / 2, 0, 0]} target={nodes.lamp_light002_Orientation.target}>
              <primitive object={nodes.lamp_light002_Orientation.target} position={[0, 0, -1]} />
            </spotLight>
          </group>
        </mesh>
        <mesh name="lamp005" castShadow receiveShadow geometry={nodes.lamp005.geometry} material={nodes.lamp005.material} position={[1.4, 5.649, -7.3]} scale={[0.25, 0.2, 0.5]}>
          <group name="lamp_light003" position={[0, -5, 0.001]} scale={[1.483, 3.75, 1.74]}>
            <spotLight visible={lightOn} castShadow angle={1.1} penumbra={0.8} decay={2} intensity={7} color="#ffe9a6" rotation={[-Math.PI / 2, 0, 0]} target={nodes.lamp_light003_Orientation.target}>
              <primitive object={nodes.lamp_light003_Orientation.target} position={[0, 0, -1]} />
            </spotLight>
          </group>
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/room with desk.glb')
