/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\assets\torch.glb -o .\src\components\Torch.jsx 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Torch(props) {
    const { nodes, materials } = useGLTF("/assets/torch.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.torch_stick.geometry}
                material={materials.torch_stick_material}
                scale={[3.2, 12.8, 3.2]}
            >
                <mesh
                    geometry={nodes.torch_off.geometry}
                    material={materials.torch_off_material}
                    position={[0, 0.078, 0]}
                    scale={[1, 0.25, 1]}
                />
                <mesh
                    geometry={nodes.torch_on.geometry}
                    material={materials["Material.001"]}
                    position={[0, 0.078, 0]}
                    scale={[1.25, 0.313, 1.25]}
                    material-emissiveIntensity={10}
                />
            </mesh>
        </group>
    );
}

useGLTF.preload("/assets/torch.glb");
