import type { DesignControl } from "@/components/design-panel/controls";

/**
 * Design variables exposed in the development-only design panel.
 * Defaults must match the values the CSS uses when no override is set.
 */
export const designControls: DesignControl[] = [
    {
        type: "range",
        key: "writing-thumb-width",
        label: "Thumbnail width",
        group: "Writing list",
        property: "--writing-thumb-width",
        min: 96,
        max: 280,
        step: 8,
        unit: "px",
        default: 176,
    },
    {
        type: "range",
        key: "writing-title-size",
        label: "Title size",
        group: "Writing list",
        property: "--writing-title-size",
        min: 14,
        max: 26,
        step: 0.5,
        unit: "px",
        default: 17,
    },
    {
        type: "range",
        key: "writing-entry-gap",
        label: "Space between entries",
        group: "Writing list",
        property: "--writing-entry-gap",
        min: 0,
        max: 64,
        step: 2,
        unit: "px",
        default: 16,
    },
    // V1 Workstation
    {
        type: "range",
        key: "home-headline-size",
        label: "Headline size",
        group: "Home",
        property: "--home-headline-size",
        min: 28,
        max: 56,
        step: 1,
        unit: "px",
        default: 34,
    },
    {
        type: "range",
        key: "home-drawing-size",
        label: "Drawing size (%)",
        group: "Home",
        property: "--home-drawing-size",
        min: 50,
        max: 110,
        step: 5,
        unit: "",
        default: 100,
    },
    {
        type: "choice",
        key: "portrait-animation",
        label: "Drawing animation",
        group: "Home",
        attribute: "data-portrait-animation",
        options: [
            { value: "on", label: "Draw in" },
            { value: "off", label: "Static" },
        ],
        default: "on",
    },
    {
        type: "choice",
        key: "drawing-fade",
        label: "Drawing fade",
        group: "Home",
        attribute: "data-drawing-fade",
        options: [
            { value: "on", label: "Soft edges" },
            { value: "off", label: "Hard edges" },
        ],
        default: "on",
    },
    {
        type: "choice",
        key: "home-drawing-mobile",
        label: "Drawing on phones",
        group: "Home",
        attribute: "data-home-drawing-mobile",
        options: [
            { value: "hidden", label: "Hidden" },
            { value: "background", label: "Background" },
        ],
        default: "hidden",
    },
    {
        type: "range",
        key: "home-drawing-bg-opacity",
        label: "Phone background opacity",
        group: "Home",
        property: "--home-drawing-bg-opacity",
        min: 0.04,
        max: 0.25,
        step: 0.01,
        unit: "",
        default: 0.08,
    },
    {
        type: "range",
        key: "screen-glow",
        label: "Laptop screen glow (%)",
        group: "Glow",
        property: "--screen-glow",
        min: 0,
        max: 300,
        step: 10,
        unit: "",
        default: 100,
    },
    {
        type: "choice",
        key: "light-surfaces",
        label: "Light surfaces",
        group: "Colour",
        attribute: "data-light-surfaces",
        options: [
            { value: "stone", label: "Stone" },
            { value: "putty", label: "Putty" },
            { value: "paper", label: "Paper" },
            { value: "current", label: "Current (neutral)" },
        ],
        default: "stone",
    },
    {
        type: "choice",
        key: "heading-font",
        label: "Heading font",
        group: "Article headings",
        attribute: "data-heading-font",
        options: [
            { value: "own", label: "Inconsolata (V1)" },
            { value: "sans", label: "Sans (V4)" },
        ],
        default: "own",
    },
    {
        type: "range",
        key: "h2-size",
        label: "H2 size",
        group: "Article headings",
        property: "--h2-size",
        min: 18,
        max: 36,
        step: 0.5,
        unit: "px",
        default: 26,
    },
    {
        type: "range",
        key: "h2-weight",
        label: "H2 weight",
        group: "Article headings",
        property: "--h2-weight",
        min: 400,
        max: 800,
        step: 10,
        unit: "",
        default: 700,
    },
    {
        type: "range",
        key: "h2-space-below",
        label: "H2 space below",
        group: "Article headings",
        property: "--h2-space-below",
        min: 8,
        max: 48,
        step: 1,
        unit: "px",
        default: 26,
    },
    {
        type: "range",
        key: "h3-size",
        label: "H3 size",
        group: "Article headings",
        property: "--h3-size",
        min: 14,
        max: 28,
        step: 0.1,
        unit: "px",
        default: 20.7,
    },
];
